name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
        env:
          CI: true

      - name: Build project
        run: yarn build

      - name: Check Docker installation
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker not found, installing Docker..."
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          else
            echo "Docker is already installed"
            docker --version
          fi

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.ACCESS_TOKEN }}
        run: |
          # Build the image
          docker build -t for-devops:${{ github.sha }} .
          echo "Docker image built successfully"
          
          # Tag for Docker Hub
          docker tag for-devops:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/for-devops:${{ github.sha }}
          docker tag for-devops:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/for-devops:latest
          
          # Login to Docker Hub
          echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          # Push to Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/for-devops:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/for-devops:latest
          
          # Output the public URL
          echo "Image URL: docker.io/${{ secrets.DOCKER_USERNAME }}/for-devops:${{ github.sha }}"
          echo "Latest Image URL: docker.io/${{ secrets.DOCKER_USERNAME }}/for-devops:latest"

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}